### ISSUE TITLE
Implement redux toolkit for global state management in './client'.

### ISSUE THREAD

**Issue by Baghel-sumit** [React-developer-want/tote_web#8]

**Comment by mprinceb** [comment]
Besides of User Profile Details what are the other things that should be managed in global state

**Comment by Baghel-sumit** [comment]
Hey @PrinceBaghel258025, We want all the props drilling thing to handled by react-redux. Before starting on it please ping we'll discuss the folder and file structure of it.

**Comment by mprinceb** [comment]
we have already implemented this issue.
